"""Add is_admin column to User model

Revision ID: f6da38515b00
Revises: f57c3be5c470
Create Date: 2024-11-13 21:16:37.048305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6da38515b00'
down_revision = 'f57c3be5c470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_price', sa.Float(), nullable=False))
        batch_op.drop_column('monthly_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_rate', sa.FLOAT(), nullable=False))
        batch_op.drop_column('monthly_price')

    # ### end Alembic commands ###
